[package]
name = "gltf"
version = "0.11.2"
authors = ["David Harvey-Macaulay <alteous@outlook.com>"]
description = "glTF 2.0 loader"
documentation = "https://docs.rs/gltf"
repository = "https://github.com/gltf-rs/gltf"
homepage = "https://github.com/gltf-rs/gltf"
readme = "README.md"
keywords = ["glTF", "3D", "asset", "model", "scene"]
license = "MIT/Apache-2.0"
include = ["**/*.rs", "Cargo.toml"]

[badges]
travis-ci = { repository = "gltf-rs/gltf" }

[workspace]
members = ["gltf-derive", "gltf-json"]

[dev-dependencies]
approx = "0.1.1"

[dependencies]
base64 = { optional = true, version = "0.6" }
byteorder = "1.1"
cgmath = "0.15"
gltf-json = { path = "gltf-json", version = "0.11.2" }
image = { optional = true, default-features = false, version = "0.19" }
lazy_static = "0.2"

[features]
default = ["import_rayon", "utils", "names"]
extras = ["gltf-json/extras"]
names = ["gltf-json/names"]
utils = []
jpeg_rayon = ["image/jpeg_rayon"]
jpeg = ["image/jpeg"]
png = ["image/png_codec"]
import = ["base64", "jpeg","png"]
import_rayon = ["base64", "jpeg_rayon","png"]
KHR_materials_pbrSpecularGlossiness = ["gltf-json/KHR_materials_pbrSpecularGlossiness"]

[[example]]
name = "gltf-display"
path = "examples/display/main.rs"

[[example]]
name = "gltf-tree"
path = "examples/tree/main.rs"
